FichasClientes/urls.py
from django.urls import path
from cliente import views

urlpatterns = [
    path('', views.index, name='index'),
    path('cliente/', views.ListaCLientesView.as_view(), name='lista_clientes'),
    path('cliente/<int:cliente_id>/', views.detalhe_cliente, name='detalhe_cliente'),
    path('cliente/novo/', views.novo_cliente, name='novo_cliente'),
    path('cliente/<int:cliente_id>/nova_compra/', views.nova_compra, name='nova_compra'),
    path('cliente/remover/<int:cliente_id>', views.remove_cliente, name= 'remover_cliente'),
    path('cliente/<int:cliente_id>/remover_compra/<int:compra_id>/', views.remove_compra, name='remover_compra'),
    path('cliente/<int:cliente_id>/pagar_conta', views.pagar_conta, name='pagar_conta'),
    path('cliente/<int:cliente_id>/historico/', views.ver_historico, name='ver_historico'),
    path('cliente/<int:cliente_id>/editar/', views.editar_cliente, name='editar_cliente'),
]

cliente/models.py
from django.db import models

class Cliente(models.Model):
    nome = models.CharField(max_length=100)
    apelido = models.CharField(max_length=100)
    cpf = models.CharField(max_length=20, blank=True, null=True)

    def __str__(self):
        return self.nome

class Compra(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    valor = models.DecimalField(max_digits=10, decimal_places=2)
    data = models.DateField(auto_now_add=True)

    def __str__(self):
        return {self.valor}
    
class Historico(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    valorTotal = models.DecimalField(max_digits=10, decimal_places=2)
    totalPago = models.DecimalField(max_digits=10, decimal_places=2)
    restante = models.DecimalField(max_digits=10, decimal_places=2)
    dataPagamento = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.totalPago

cliente/forms.py
from django import forms
from .models import Cliente, Compra

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['nome', 'apelido', 'cpf']

class CompraForm(forms.ModelForm):
    class Meta:
        model = Compra
        fields = ['valor']

cliente/views.py
from decimal import Decimal
from django.shortcuts import render, get_object_or_404, redirect
from .models import Cliente, Compra, Historico
from .forms import ClienteForm, CompraForm
from django.views.generic import ListView
from django.db.models import Q

def index(request):
    return render(request, 'cliente/index.html')

class ListaCLientesView(ListView):
    model = Cliente
    template_name = 'cliente/lista_clientes.html'
    context_object_name = 'clientes'
    
    def get_queryset(self):
        queryset = super().get_queryset().order_by('nome')
        txt_nome = self.request.GET.get('nome')
        if txt_nome:
            queryset = queryset.filter(Q(nome__icontains=txt_nome) | Q(apelido__icontains=txt_nome))
        return queryset

def detalhe_cliente(request, cliente_id):
    cliente = get_object_or_404(Cliente, pk=cliente_id)
    compras = Compra.objects.filter(cliente=cliente)
    total = sum(compra.valor for compra in compras)
    return render(request, 'cliente/detalhe_cliente.html', {'cliente': cliente, 'compras': compras, 'total': total})

def novo_cliente(request):
    if request.method == 'POST':
        form = ClienteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('lista_clientes')
    else:
        form = ClienteForm()
    return render(request, 'cliente/novo_cliente.html', {'form': form})

def nova_compra(request, cliente_id):
    cliente = get_object_or_404(Cliente, pk=cliente_id)
    if request.method == 'POST':
        form = CompraForm(request.POST)
        if form.is_valid():
            compra = form.save(commit=False)
            compra.cliente = cliente
            compra.save()
            return redirect('detalhe_cliente', cliente_id = cliente.id)
    else:
        form = CompraForm()
    return render(request, 'cliente/nova_compra.html', {'cliente': cliente, 'form': form })

def remove_cliente(request, cliente_id):
    cliente = get_object_or_404(Cliente, id=cliente_id)
    if request.method == 'POST':
        cliente.delete()
        return redirect('lista_clientes')
    return render(request, 'cliente/remover_cliente.html', {'cliente': cliente})

def remove_compra(request, cliente_id, compra_id):
    cliente = get_object_or_404(Cliente, id=cliente_id)
    compra = get_object_or_404(Compra, id=compra_id)
    if request.method == 'POST':
        compra.delete()
        return redirect('detalhe_cliente', cliente_id=cliente_id)
    return render(request, 'cliente/remover_compra.html', {'cliente': cliente, 'compra': compra})

def remover_todas_compras(cliente_id):
    cliente = get_object_or_404(Cliente, id=cliente_id)
    compra = Compra.objects.filter(cliente=cliente)
    for compras in compra:
        compras.delete()

def restante_conta(cliente, valor):
    restante_conta = Compra(cliente=cliente, valor=valor)
    restante_conta.save()
    return restante_conta

def pagar_conta(request, cliente_id):
    cliente = get_object_or_404(Cliente, id=cliente_id)
    compras = Compra.objects.filter(cliente = cliente)

    if request.method == 'POST':
        valorPago = Decimal(request.POST.get('valorPago'))
        total = sum(compra.valor for compra in compras)

        if total > valorPago:
            restante = total - valorPago
            remover_todas_compras(cliente_id)
            Historico.objects.create(cliente=cliente, valorTotal=total, totalPago=valorPago, restante=restante)
            restante_conta(cliente, restante)
        else:
            remover_todas_compras(cliente_id)
            Historico.objects.create(cliente=cliente, valorTotal=total, totalPago=valorPago, restante=Decimal('0.00'))

        return redirect('detalhe_cliente', cliente_id=cliente_id)
    
    return render(request, 'cliente/pagar_conta.html', {'cliente': cliente, 'compras': compras})     

def ver_historico(request, cliente_id):
    cliente = get_object_or_404(Cliente, pk=cliente_id)
    historico = Historico.objects.filter(cliente=cliente)
    return render(request, 'cliente/historico.html', {'cliente': cliente, 'historico': historico})

def editar_cliente(request, cliente_id):
    cliente = get_object_or_404(Cliente, pk=cliente_id)
    if request.method == 'POST':
        cliente.nome = request.POST.get('name')
        cliente.apelido = request.POST.get('apelido')
        cliente.cpf = request.POST.get('cpf')
        cliente.save()
        return redirect('detalhe_cliente', cliente_id=cliente_id)
    return render(request, 'cliente/editar.html', {'cliente': cliente})

cliente/templates/cliente/base.html
<!doctype html>
<html lang="pt-br" class="h-100">
    <head>
        <title>{% block tittle %} Caderneta Virtual {% endblock %}</title>
        <!-- Required meta tags -->
        <meta charset="utf-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />

        <!-- Bootstrap CSS v5.2.1 -->
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
            crossorigin="anonymous"
        />
    </head>

    <body class="d-flex h-100">
        <header class="d-flex flex-column align-items-stretch flex-shrink-0 p-3" style="background-color: #084298; max-width:300px">
            <div class="mb-4">
                <h1 class="info text-center"><a href="{% url 'index' %}" class="link-light link-underline-opacity-0">CADERNETA VIRTUAL</a></h1>
            </div>
            <ul class="list-unstyled components mb-5">
                <li class="active">
                    <p class="bg-light">
                        <a href="{% url 'lista_clientes' %}" class="nav-link icon-link icon-link-hover link-primary" style="--bs-icon-link-transform: translate3d(0, -.125rem, 0);" href="#">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
                                <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8M1.173 8a13 13 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5s3.879 1.168 5.168 2.457A13 13 0 0 1 14.828 8q-.086.13-.195.288c-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5s-3.879-1.168-5.168-2.457A13 13 0 0 1 1.172 8z"/>
                                <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5M4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0"/>
                              </svg>
                            Ver Clientes
                        </a>
                    </p>
                </li>
                <li>
                    <p class="bg-light">
                        <a href="{% url 'novo_cliente' %}" class="nav-link icon-link icon-link-hover link-primary" style="--bs-icon-link-transform: translate3d(0, -.125rem, 0);" href="#">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-lg" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M8 2a.5.5 0 0 1 .5.5v5h5a.5.5 0 0 1 0 1h-5v5a.5.5 0 0 1-1 0v-5h-5a.5.5 0 0 1 0-1h5v-5A.5.5 0 0 1 8 2"/>
                          </svg>
                            Novo Cliente
                        </a>
                    </p>
                </li>
            </ul>
        </header>

        <main class="flex-grow-1 p-4 d-flex flex-column">
            {% block content %}
            {% endblock %}
        </main>

        <!-- Bootstrap JavaScript Libraries -->
        <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
            crossorigin="anonymous"
        ></script>

        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
            integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
            crossorigin="anonymous"
        ></script>
    </body>
</html>

cliente/templates/cliente/detalhe_cliente.html
{% extends "./base.html" %}
{% block tittle %} Detalhes {% endblock %}

{% block content %}
    <div class="text-center">
        <h1> Detalhes do Cliente </h1>
    </br>
    </div>
    <table class="table table-borderless border border-secondary text-center">
      <thead>
        <tr>
          <th class="p-3" scope="col">NOME</th>
          <th class="p-3" scope="col">APELIDO</th>
          <th class="p-3" scope="col">CPF</th>
          <th class="p-3" scope="col">OPÇÕES</th>
          </tr>
      </thead>
      <tbody>
        <tr>
          <td class="p-3" > {{ cliente.nome }} </td>
          <td class="p-3" > {{ cliente.apelido }} </td>
          <td class="p-3" > {{ cliente.cpf }} </td>
          <td class=" p-3" > 
              <a href="{% url 'ver_historico' cliente.id %}" class="btn btn-secondary"> 
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-card-list" viewBox="0 0 16 16">
                  <path d="M14.5 3a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2z"/>
                  <path d="M5 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 5 8m0-2.5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5m0 5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5m-1-5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0M4 8a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0m0 2.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0"/>
                </svg>              </a>
              <a href="{% url 'remover_cliente' cliente.id %}" class="btn btn-danger"> 
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                  <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47M8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5"/>
                </svg>
              </a>
          </td>
        </tr>
      </tbody>
    </table>
    
    <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Valor</th>
            <th scope="col">Data</th>
            <th scope="col" class="text-end">Opções</th>
          </tr>
        </thead>
        <tbody>
            {% for compra in compras %}  
            <tr>
              <th scope="row">{{ compra.id }}</th>
              <td>{{ compra.valor }}</td>
              <td>{{ compra.data }}</td>
              <td class="text-end">
                <a href="{% url 'remover_compra' cliente.id compra.id %}" class="btn btn-danger"> 
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                    <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47M8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5"/>
                  </svg>
                </a>
              </td>
            </tr>
            {% empty %}
            <tr>
              <td colspan="4"> Nenhuma compra registrada </td>
            </tr>
            {% endfor %}
        </tbody>
    </table> 
    <footer class="d-flex bd-highlight mt-5 p-2 bg-light">
        <h3 class="p-2 flex-grow-1 bd-highlight">Total: {{ total }}</h3>
        <a href="{% url 'nova_compra' cliente.id %}" class="btn btn-primary p-3 bd-highlight me-2">Nova Compra</a>
        <a href="{% url 'pagar_conta' cliente.id%}" class="btn btn-success p-3 bd-highlight">Pagar conta</a>
    </footer>
{% endblock %}

cliente/templates/cliente/editar.html
{% extends "./base.html" %}
{% block tittle %} Editar {% endblock %}

{% block content %}
    <h4> Cliente "{{ cliente.nome }}" - Editar</h4>
    <form action="{% url 'editar_cliente' cliente.id %}" method="POST">
        {% csrf_token %}
        <p>
            <label for="id_nome">
                Novo nome:
            </label>
            <input id="id_nome" type="text" name="name" required"" value="{{cliente.nome}}">
        </p>
        <p>
            <label for="id_apelido">
                Novo apelido:
            </label>
            <input id="id_apelido" type="text" name="apelido" required="" value="{{cliente.apelido}}">
        </p>
        <p>
            <label for="id_cpf">
                novo cpf:
            </label>
            <input id="id_cpf" type="text" name="cpf" required="" value="{{cliente.cpf}}">
        </p>

        <button type="submit" class="btn btn-success">
            Confirmar
        </button>
        <a
            href="{% url 'detalhe_cliente' cliente.id %}" class="btn btn-danger"
        >
            Cancelar
        </a>   
    </form>
{% endblock %}

cliente/templates/cliente/historico.html
{% extends "./base.html" %}
{% block tittle %} Histórico {% endblock %}

{% block content %}
    <div class="text-center">
        <h1> Histórico - {{ cliente.apelido }} </h1>
    </br>
    </div>
    
    <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Valor Total</th>
            <th scope="col">Valor Pago</th>
            <th scope="col">Restante</th>
            <th scope="col">Data pagamento</th>
          </tr>
        </thead>
        <tbody>
            {% for historicos in historico %}  
            <tr>
              <td>{{ historicos.valorTotal }}</td>
              <td>{{ historicos.totalPago}}</td>
              <td>{{ historicos.restante}}</td>
              <td>{{ historicos.dataPagamento}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table> 
    <footer class="d-flex bd-highlight mt-5 p-2 bg-light">
        <h3 class="p-2 flex-grow-1 bd-highlight">Total: {{ total }}</h3>
        <a href="{% url 'nova_compra' cliente.id %}" class="btn btn-primary p-3 bd-highlight me-2">Nova Compra</a>
        <a href="{% url 'pagar_conta' cliente.id%}" class="btn btn-success p-3 bd-highlight">Pagar conta</a>
    </footer>
{% endblock %}

cliente/templates/cliente/index.html
{% extends './base.html' %}

{% block title %}Página Inicial{% endblock %}

{% block content %}
<div class="container text-center">
    <h1><p>Logo do projeto</p></h1>
</div>
{% endblock %}

cliente/templates/cliente/lista_clientes.html
{%extends "./base.html"%}

{% block title %}Página Inicial{% endblock %}

{% block content %}
    <div class="text-center">
        <h1>Lista de Clientes</h1>
    </br>
    </div>
    <form action="?" method"GET">
        <input type="text" name="nome" id="" value="{{ request.GET.nome }}" autocomplete="off">
        <button type="submit" class="btn btn-success"> BUSCAR </button>
        <a href="{% url 'lista_clientes'%}" class="btn btn-dark"> Limpar </a>
    </form>
    <hr>
    <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Nome</th>
            <th scope="col">Apelido</th>
            <th scope="col" class="text-end">Opções</th>
          </tr>
        </thead>
        <tbody>
            {% for cliente in clientes %}  
            <div class="d-grid gap-2">
                <tr>
                    <th scope="row">{{ cliente.id }}</th>
                    <td>{{ cliente.nome }}</td>
                    <td>{{ cliente.apelido }}</td>
                    <td class="text-end">
                        <a href="{% url 'detalhe_cliente' cliente.id %}" class="btn btn-info">Ver</a>
                        <a href="{% url 'editar_cliente' cliente.id %}" class="btn btn-secondary">Editar</a>
                    </td>
                </tr>
            </div>
            </a>
            {% endfor %}
        </tbody>
    </table> 
{% endblock %}

cliente/templates/cliente/nova_compra.html
{% extends "./base.html" %}

{% block tittle %} Nova Compra {% endblock %}

{% block content %}
    <div class="text-center">
        <h1> Nova Compra - {{ cliente.apelido }}</h1>
        </br>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success">Registrar</button>
        </form>
    </div>
{% endblock %}

cliente/templates/cliente/novo_cliente.html
{% extends "./base.html" %}

{% block tittle %} Novo  Cliente {% endblock %}

{% block content %}
    <div class="text-center">
        <h1>Cadastrar Novo Cliente</h1>
        </br>
    </div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Salvar</button>
    </form>
{% endblock %}

cliente/templates/cliente/pagar_conta.html
{% extends "./base.html" %}
{% block tittle %} Detalhes {% endblock %}

{% block content %}
    <h4> Cliente "{{ cliente.nome }}" - Pagar conta</h4>
    <h3> Total: {{ total }} </h3>
    <form action="{% url 'pagar_conta' cliente.id %}" method="POST">
        {% csrf_token %}
        <p>
            <label for="id_valorPago">
                Valor:
            </label>
            <input id="id_valorPago" type="number" name="valorPago" step="0.01" required="">
        </p>
        <button type="submit" class="btn btn-success">
            Pagar
        </button>
        <a
            href="{% url 'detalhe_cliente' cliente.id %}" class="btn btn-danger"
        >
            Cancelar
        </a>   
    </form>
{% endblock %}

cliente/templates/cliente/remover_cliente.html
{% extends "./base.html" %}
{% block tittle %} Detalhes {% endblock %}

{% block content %}
    <h4> Deseja mesmo deletar o cliente "{{ cliente.nome }}" </h4>
    <form action="{% url 'remover_cliente' cliente.id %}" method="POST">
        {% csrf_token %}
        <button
            type="submit"
            class="btn btn-primary"
        >
            Sim
        </button>
        <a
            href="{% url 'detalhe_cliente' cliente.id %}" class="btn btn-danger"
        >
            Cancelar
        </a>   
    </form>
{% endblock %}

cliente/templates/cliente/remover_compra.html
{% extends "./base.html" %}
{% block tittle %} Detalhes {% endblock %}

{% block content %}
    <h4> Deseja mesmo deletar esta compra? "{{ compra.valor }}" </h4>
    <form action="{% url 'remover_compra' cliente.id compra.id %}" method="POST">
        {% csrf_token %}
        <button
            type="submit"
            class="btn btn-primary"
        >
            Sim
        </button>
        <a
            href="{% url 'detalhe_cliente' cliente.id %}" class="btn btn-danger"
        >
            Cancelar
        </a>   
    </form>
{% endblock %}